### ISSUE TITLE
Login isssues on fedora 40

### ISSUE THREAD

**Issue by n1lby73** [thiagojolv/packettracer-fedora#58]
After installing with the script, when i try launching the app - it requires that i login into my cisco or skill for all account buh at the end of the day i end up with a 404 error page after a succesful login. closing the 404 page still tells the packet tracer that i'm not logged in thus crashing the application

**Comment by thiagojolv** [comment]
This is not problem of the script. Maybe the cisco's servers have a temporary instability in the moment that you were trying.

**Comment by n1lby73** [comment]
logging in with skillsforall did the trick
