### ISSUE TITLE
Installing Fails

### ISSUE THREAD

**Issue by taynotfound** [thiagojolv/packettracer-fedora#62]
Selected installer: /home/tay/Downloads/Packet_Tracer822_amd64_signed.deb 

Removing old version of Packet Tracer from /opt/pt
Cisco Packet Tracer was uninstalled.
Installing dependencies
Updating and loading repositories:
Repositories loaded.
Package "binutils-2.43.1-4.fc41.x86_64" is already installed.
Package "qt5-qtmultimedia-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtwebengine-5.15.17-11.fc41.x86_64" is already installed.
Package "qt5-qtnetworkauth-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtwebsockets-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtwebchannel-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtscript-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtlocation-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtsvg-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtspeech-5.15.15-1.fc41.x86_64" is already installed.

Nothing to do.
Extracting files
ar: /home/tay/Downloads/Packet_Tracer822_amd64_signed.deb: file format not recognized
tar: packettracer/control.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: packettracer/data.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
cp: cannot stat 'packettracer/usr': No such file or directory
cp: cannot stat 'packettracer/opt': No such file or directory
sed: can't read ./packettracer/postinst: No such file or directory
sed: can't read ./packettracer/postinst: No such file or directory
sed: can't read ./packettracer/postinst: No such file or directory
sudo: ./packettracer/postinst: command not found
sed: can't read /usr/share/applications/cisco-pt*.desktop: No such file or directory

**Comment by thiagojolv** [comment]
Hello!
How did you run the installer? I cannot reproduce this issue. See what happened with me:
```bash
jack@thinkpad-x1:~/Projects/packettracer-fedora$ sudo bash setup.sh 
Searching for installers in user home...

Selected installer: /home/jack/Downloads/Packet_Tracer822_amd64_signed.deb 

Removing old version of Packet Tracer from /opt/pt
Uninstalling Cisco Packet Tracer.
gtk-update-icon-cache: Cache file created successfully.
Cisco Packet Tracer was uninstalled.
Installing dependencies
Updating and loading repositories:
Repositories loaded.
Package "binutils-2.43.1-5.fc41.x86_64" is already installed.
Package "qt5-qtmultimedia-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtwebengine-5.15.17-11.fc41.x86_64" is already installed.
Package "qt5-qtnetworkauth-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtwebsockets-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtwebchannel-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtscript-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtlocation-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtsvg-5.15.15-1.fc41.x86_64" is already installed.
Package "qt5-qtspeech-5.15.15-1.fc41.x86_64" is already installed.

Nothing to do.
Extracting files
./
./control
./postinst
./postrm
./preinst
./templates
./
...
```

**Comment by thiagojolv** [comment]
Comparing your log with mine, the version of binutils is only the difference with mine. Can you try running an update to get the version 2.43.1-5?

**Comment by taynotfound** [comment]
Yes i'll Check later. Will keep you up to date

Tayron März
https://taymaerz.de
